# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pull-request
  description: Runs manually for pull requests
spec:
  type: buildkite-pipeline
  owner: 'group:kibana-operations'
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: kibana / pull request
      description: Runs manually for pull requests
    spec:
      env:
        PR_COMMENTS_ENABLED: 'true'
        GITHUB_BUILD_COMMIT_STATUS_ENABLED: 'true'
        GITHUB_BUILD_COMMIT_STATUS_CONTEXT: kibana-ci
        GITHUB_STEP_COMMIT_STATUS_ENABLED: 'true'
      branch_configuration: ''
      cancel_intermediate_builds: true
      default_branch: main
      repository: elastic/kibana
      pipeline_file: .buildkite/scripts/pipelines/pull_request/pipeline.sh
      provider_settings:
        build_branches: false
        build_pull_requests: true
        publish_commit_status: false
        skip_pull_request_builds_for_existing_commits: false
        trigger_mode: none
        build_tags: false
      teams:
        everyone:
          access_level: MANAGE_BUILD_AND_READ
