# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: single_user_performance
  description: Runs single user performance tests for kibana
spec:
  type: buildkite-pipeline
  owner: 'group:kibana-operations'
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: kibana / single-user-performance
      description: Runs single user performance tests for kibana
    spec:
      env:
        SLACK_NOTIFICATIONS_CHANNEL: '#kibana-performance-alerts'
        SLACK_NOTIFICATIONS_ENABLED: 'true'
        BAZEL_CACHE_MODE: none
      branch_configuration: main
      default_branch: main
      repository: elastic/kibana
      pipeline_file: .buildkite/pipelines/performance/daily.yml
      provider_settings: {}
      teams:
        everyone:
          access_level: MANAGE_BUILD_AND_READ
      schedules:
        Single user daily test:
          cronline: 0 */3 * * * Europe/Berlin
          message: Single user daily test
          branch: main
