# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: performance_data_set_extraction
  description: Runs single user performance tests and extract APM traces
spec:
  type: buildkite-pipeline
  owner: 'group:kibana-operations'
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: kibana / performance-data-set-extraction
      description: Runs single user performance tests and extract APM traces
    spec:
      env:
        SLACK_NOTIFICATIONS_CHANNEL: '#kibana-performance-alerts'
        SLACK_NOTIFICATIONS_ENABLED: 'true'
        BAZEL_CACHE_MODE: none
      branch_configuration: main
      default_branch: main
      repository: elastic/kibana
      pipeline_file: .buildkite/pipelines/performance/data_set_extraction_daily.yml
      provider_settings: {}
      teams:
        everyone:
          access_level: MANAGE_BUILD_AND_READ
      schedules:
        Extract APM traces:
          cronline: 0 3/8 * * * Europe/Berlin
          message: Extract APM traces
          branch: main
