# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: serverless-emergency-release-branch-testing
  description: Runs testing for emergency release / hotfix branches
spec:
  type: buildkite-pipeline
  owner: 'group:kibana-operations'
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: kibana / serverless / emergency release branch testing
      description: Runs testing for emergency release / hotfix branches
    spec:
      env:
        SLACK_NOTIFICATIONS_CHANNEL: '#kibana-mission-control'
        SLACK_NOTIFICATIONS_ENABLED: 'true'
      branch_configuration: deploy-fix@*
      default_branch: main
      repository: elastic/kibana
      pipeline_file: .buildkite/pipelines/es_serverless/emergency_release_branch_testing.yml
      provider_settings:
        build_branches: true
        build_pull_requests: false
        publish_commit_status: true
        skip_pull_request_builds_for_existing_commits: false
        trigger_mode: code
        build_tags: false
        skip_builds_for_existing_commits: true
      teams:
        everyone:
          access_level: MANAGE_BUILD_AND_READ
