apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: kibana-buildkite-pipelines
  description: This file points to individual buildkite pipeline definition files
spec:
  type: url
  targets:
    - kibana-api-docs.yaml
    - kibana-apis-capacity-testing-daily.yaml
    - kibana-artifacts-trigger.yaml
    - kibana-artifacts.yaml
    - kibana-buildkite.yaml
    - kibana-ci-stats.yaml
    - kibana-custom-node-build.yaml
    - kibana-daily.yaml
    - kibana-demo-env.yaml
    - kibana-es-snapshots.yaml
    - kibana-flaky.yaml
    - kibana-fleet-packages-daily.yaml
    - kibana-hourly.yaml
    - kibana-on-merge-unsupported-ftrs.yaml
    - kibana-on-merge.yaml
    - kibana-packer.yaml
    - kibana-performance-daily.yaml
    - kibana-performance-data-set-extraction-daily.yaml
    - kibana-pr.yaml
    - kibana-purge-cloud-deployment.yaml
    - kibana-purge-cloud-deployments.yaml
    - kibana-remote-dev-packer.yaml
    - kibana-serverless-release-testing.yaml
    - kibana-serverless-release.yaml
    - kibana-serverless-security-solution-quality-gate-api-integration.yaml
    - kibana-serverless-security-solution-quality-gate-edr-workflows.yaml
    - kibana-serverless-security-solution-quality-gate.yaml
    - kibana-serverless.yaml
    - scalability_testing-daily.yaml
