env:
  PUBLISH_API_DOCS_CHANGES: 'true'
steps:
  - commands:
      - .buildkite/scripts/bootstrap.sh
      - node scripts/type_check
    label: Run scripts/type_check to ensure that all build available
    key: type_check
    agents:
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      provider: gcp
      machineType: n2-standard-8
      preemptible: true
    timeout_in_minutes: 60

  - command: .buildkite/scripts/steps/build_api_docs.sh
    label: 'Build API Docs'
    agents:
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      provider: gcp
      machineType: n2-standard-4
      preemptible: true
    key: build_api_docs
    depends_on: type_check
    timeout_in_minutes: 30
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
